const navigationLinks = [
    { text: "Home", url: "#" },
    { text: "About", url: "#" },
    {
      text: "Shop",
      url: "#",
      subLinks: [
        { text: "All Products", url: "#" },
        { text: "Popular Items", url: "#" },
        { text: "New Arrivals", url: "#" },
      ],
    },
  ];
  
  const product_list = [
    {
      img: "https://www.tcscricket.com/wp-content/uploads/2022/06/MRF-GRAND-LIMITED-EDITION-ENGLISH-WILLOW-CRICKET-BAT-1-768x768.jpg",
      title: "Cricket Bat",
      id:1.5,
      sale: "Sale",
      rating:4.5,
      newprice: 1000.0,
    },
    {
      img: "https://m.media-amazon.com/images/I/71snlkNDRBL._SX679_.jpg",
      title: "Shuttle",
      id:2,
      rating:3.9,
      oldprice: 400.0,
      newprice: 340.0,
    },
    {
      img: "https://i5.walmartimages.com/seo/Wilson-Burn-Pink-25-in-Junior-Tennis-Racket-Ages-9-10_6f2317be-6133-4a23-8125-2ce46285260c.851da120f1cb97923c875bfb49af7f90.png",
      title: "Tennis",
      id:3,
      rating:4.2,
      oldprice: 700.0,
      newprice: 500.0,
    },
    {
      img: "https://www.cooperstownbat.com/wp-content/uploads/2020/11/Youth-Pink-600x600.jpg",
      title: "Baseball Bat",
      id:4,
      rating:3.5,
      newprice: 420.0,
    },
    {
      img: "https://cdn.nwscdn.com/media/catalog/product/cache/h700xw700/b/l/black-c70-main.jpg",
      title: "Hockey Stick",
      id:5,
      rating:4.9,
      sale: "Sale",
      oldprice: 500.0,
      newprice: 400.0,
    },
    {
      img: "https://www.skatesupplyindia.com/cdn/shop/files/WeChat79643b4f23fed6045e6263dd73c4daca.jpg?v=1696684622",
      title: "Skate Board",
      id:6,
      rating:3.3,
      newprice: 120.0,
    },
    {
      img: "https://m.media-amazon.com/images/I/81Ks1unc9GL._SX679_.jpg",
      title: "Yoga mat",
      id:7,
      rating:5,
      sale: "Sale",
      oldprice: 203.0,
      newprice: 183.0,
    },
    {
      img: "https://m.media-amazon.com/images/I/412kTcCMJpL._SX679_.jpg",
      title: "Exersise Band",
      id:8,
      rating:4,
      newprice: 405.0,
    },
    {
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Football_Pallo_valmiina-cropped.jpg/255px-Football_Pallo_valmiina-cropped.jpg",
      title: "Football",
      id:9,
      rating:4.0,
      newprice: 490.0,
    },
    {
      img: "https://upload.wikimedia.org/wikipedia/commons/thumb/7/7a/Basketball.png/330px-Basketball.png",
      title: "Basketball",
      id:10,
      rating:4.5,
      sale: "Sale",
      oldprice: 205.0,
      newprice: 184.0,
    },
    {
      img: "https://cdn.nwscdn.com/media/catalog/product/cache/h700xw700/f/o/forza_size_5_competition_standard_volleyball_for_all_volleyball_tournaments_and_matches.jpg",
      title: "Volleyball",
      id:11,
      rating:4.7,
      sale: "Sale",
      oldprice: 504.0,
      newprice: 254.0,
    },
    {
      img: "https://www.jiomart.com/images/product/original/rv7cg2hp4t/stag-5-star-table-tennis-racquet-product-images-orv7cg2hp4t-p597754697-0-202306221715.jpg?im=Resize=(420,420)",
      title: "Table tennis",
      id:12,
      rating:3.5,
      newprice: 404.0,
    },
    {
      img: "https://fitnessone.in/wp-content/uploads/2023/05/best-gym-ball.png",
      title: "Exercise ball",
      id:13,
      rating:4.0,
      sale: "Sale",
      oldprice: 350.0,
      newprice: 254.0,
    },
    {
      img: "https://m.media-amazon.com/images/I/51uDz-BJ7jS.jpg",
      title: "Cricket Accessories",
      id:14,
      rating:1,
      newprice: 2020.0,
    },
    {
      img: "https://images.meesho.com/images/products/193704618/fbpzf_512.webp",
      title: "Sponge ball",
      id:15,
      rating:3,
      sale: "sale",
      oldprice: 20.0,
      newprice: 18.0,
    },
    {
      img: "https://contents.mediadecathlon.com/p1592998/c901b69179d40a0c2d013d8880a994f7/p1592998.jpg?format=auto&quality=70&f=650x0",
      title: "Boxing",
      id:16,
      rating:2,
      newprice: 405.0,
    },
  ];
  export { product_list, navigationLinks };